/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SolicitarRouteImport } from './routes/solicitar'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminLembretesRouteImport } from './routes/_authenticated/admin.lembretes'
import { Route as AuthenticatedAdminOrdensIndexRouteImport } from './routes/_authenticated/admin.ordens.index'
import { Route as AuthenticatedAdminOrdensIdRouteImport } from './routes/_authenticated/admin.ordens.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitarRoute = SolicitarRouteImport.update({
  id: '/solicitar',
  path: '/solicitar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/admin/clientes',
    path: '/admin/clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminLembretesRoute =
  AuthenticatedAdminLembretesRouteImport.update({
    id: '/admin/lembretes',
    path: '/admin/lembretes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOrdensIndexRoute =
  AuthenticatedAdminOrdensIndexRouteImport.update({
    id: '/admin/ordens/',
    path: '/admin/ordens/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOrdensIdRoute =
  AuthenticatedAdminOrdensIdRouteImport.update({
    id: '/admin/ordens/$id',
    path: '/admin/ordens/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/solicitar': typeof SolicitarRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/lembretes': typeof AuthenticatedAdminLembretesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/ordens/$id': typeof AuthenticatedAdminOrdensIdRoute
  '/admin/ordens/': typeof AuthenticatedAdminOrdensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/solicitar': typeof SolicitarRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/lembretes': typeof AuthenticatedAdminLembretesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/ordens/$id': typeof AuthenticatedAdminOrdensIdRoute
  '/admin/ordens': typeof AuthenticatedAdminOrdensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/solicitar': typeof SolicitarRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/lembretes': typeof AuthenticatedAdminLembretesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/ordens/$id': typeof AuthenticatedAdminOrdensIdRoute
  '/_authenticated/admin/ordens/': typeof AuthenticatedAdminOrdensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/solicitar'
    | '/admin/clientes'
    | '/admin/dashboard'
    | '/admin/leads'
    | '/admin/lembretes'
    | '/admin/'
    | '/admin/ordens/$id'
    | '/admin/ordens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/solicitar'
    | '/admin/clientes'
    | '/admin/dashboard'
    | '/admin/leads'
    | '/admin/lembretes'
    | '/admin'
    | '/admin/ordens/$id'
    | '/admin/ordens'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/solicitar'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/lembretes'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/ordens/$id'
    | '/_authenticated/admin/ordens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SolicitarRoute: typeof SolicitarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitar': {
      id: '/solicitar'
      path: '/solicitar'
      fullPath: '/solicitar'
      preLoaderRoute: typeof SolicitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/lembretes': {
      id: '/_authenticated/admin/lembretes'
      path: '/admin/lembretes'
      fullPath: '/admin/lembretes'
      preLoaderRoute: typeof AuthenticatedAdminLembretesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ordens/': {
      id: '/_authenticated/admin/ordens/'
      path: '/admin/ordens'
      fullPath: '/admin/ordens/'
      preLoaderRoute: typeof AuthenticatedAdminOrdensIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ordens/$id': {
      id: '/_authenticated/admin/ordens/$id'
      path: '/admin/ordens/$id'
      fullPath: '/admin/ordens/$id'
      preLoaderRoute: typeof AuthenticatedAdminOrdensIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminLembretesRoute: typeof AuthenticatedAdminLembretesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminOrdensIdRoute: typeof AuthenticatedAdminOrdensIdRoute
  AuthenticatedAdminOrdensIndexRoute: typeof AuthenticatedAdminOrdensIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminLembretesRoute: AuthenticatedAdminLembretesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminOrdensIdRoute: AuthenticatedAdminOrdensIdRoute,
  AuthenticatedAdminOrdensIndexRoute: AuthenticatedAdminOrdensIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SolicitarRoute: SolicitarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}